services:
  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=production
    ports: 
      - 80:19006


  backend:
    build: ./backend
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
