services:
  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/opt/the_void
    ports: 
      - 19006:19006

  backend:
    build: ./backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 5001:5001