services:
  backend:
    container_name: backend
    build: ./backend
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000

  frontend:
    container_name: frontend
    build: ./frontend
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend/web-build:/opt/the-void/web-build
    command: npx expo export:web

  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs/:/etc/logs/
      - ./frontend/web-build:/usr/share/nginx/html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/logs:/var/log/letsencrypt
    command: certonly --webroot -w /var/www/certbot --email ${EMAIL} -d ${DOMAIN} --agree-tos